theme: jekyll-theme-midnight
title: Bryan Poteryko
description: A website dedicated to showcasing my engineering projects, particularly in the field of robotics. My degree in Engineering Physics gives me skills from mechanical, electrical, and software engineering, giving me great flexibility.