theme: jekyll-theme-midnight
title: Bryan Poteryko Project Portfolio
description: A website dedicated to showcasing my engineering projects. I particularly enjoy the field of robotics, as it allows for the fusion of mechanical, electrical, and software design, all of which I have worked to developed over the course of my degree in Engineering Physics.
