theme: jekyll-theme-midnight
title: Bryan Poteryko Project Portfolio
description: A website dedicated to showcasing my engineering projects, particularly in the field of robotics, as it allows for my skills in mechanical, electrical, and software design to shine.